In [1]:
import numpy as np


In [3]:
my_lst = [1,2,3,4,5]

In [5]:
arr = np.array(my_lst)

In [7]:
arr

array([1, 2, 3, 4, 5])

In [11]:
print(arr)

[1 2 3 4 5]


In [19]:
arr=arr.reshape(5,1)

In [21]:
print(arr)

[[1]
 [2]
 [3]
 [4]
 [5]]


In [23]:
a = [1,2,3,4,5]

In [25]:
b= [6,9,10,11,15]
c=[3,6,8,4,98]

In [33]:
arr1 = np.array([a,b,c])

In [35]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  9, 10, 11, 15],
       [ 3,  6,  8,  4, 98]])

In [37]:
print(arr1)

[[ 1  2  3  4  5]
 [ 6  9 10 11 15]
 [ 3  6  8  4 98]]


In [55]:
np.arange(1,99,8).reshape(13,1)

array([[ 1],
       [ 9],
       [17],
       [25],
       [33],
       [41],
       [49],
       [57],
       [65],
       [73],
       [81],
       [89],
       [97]])

In [49]:
np.ones((4,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [57]:
np.random.rand(3,3)

array([[0.09268655, 0.6778679 , 0.41272207],
       [0.46307657, 0.83145571, 0.77752297],
       [0.76449258, 0.30413747, 0.41818484]])

In [59]:
np.random.randn(3,3)

array([[ 0.86141739,  0.16622188, -1.04259907],
       [-0.09099462,  1.23430244, -0.32436082],
       [-1.91261618,  0.10770045, -0.64215875]])